name: capstone

description: "A local+remote notes management CLI app using Dart."

environment:
  sdk: '^3.1.0'

dependencies:
  json_annotation: any

dev_dependencies:
  json_serializable: any
  build_runner: any
  http: ^1.1.0
  uuid: ^4.4.2
